django_project/backend/urls.py
from django.conf.urls import patterns, url
from .views import (
    PoiList,
    PoiEdit,
    PoiAdd,
    GetRelatedWorktime,
    AdAdd,
    AdList,
    AdEdit,
    CategoriesList,
    CategoriesEdit,
    CategoriesAdd,
    DeletePoi,
    DeleteAd,
    DeleteCategory,
    LoginBackend,
    LogoutBackend,
    GetRelatedPrices,
    FeatureAdd,
    FeatureList,
    FeatureEdit,
    DeleteFeature,
    AmenityAdd,
    AmenityList,
    AmenityEdit,
    DeleteAmenity,
    PlaceList,
    PlaceAdd,
    PlaceEdit,
    DeletePlace
)

urlpatterns = patterns(
    '',
    # basic app views
    # url(r'^...', a_view)
    url(r'^cp/$', PoiList.as_view(), name='PoiList'),
    url(r'^cp/edit/(?P<pk>\d+)/$', PoiEdit.as_view(), name='PoiEdit'),
    url(r'^cp/add/$', PoiAdd.as_view(), name='PoiAdd'),
    url(r'^cp/get_worktime/$', GetRelatedWorktime.as_view()),
    url(r'^cp/add_ad/$', AdAdd.as_view(), name='AdAdd'),
    url(r'^cp/list_ad/$', AdList.as_view(), name='AdList'),
    url(r'^cp/edit_ad/(?P<pk>\d+)/$', AdEdit.as_view(), name='AdEdit'),
    url(r'^cp/list_cat/$', CategoriesList.as_view(), name='CategoriesList'),
    url(r'^cp/add_cat/$', CategoriesAdd.as_view(), name='CategoriesAdd'),
    url(
        r'^cp/edit_cat/(?P<pk>\d+)/$',
        CategoriesEdit.as_view(),
        name='CategoriesEdit'
    ),
    url(r'^cp/del/poi/(?P<pk>\d+)/$', DeletePoi.as_view(), name='PoiDel'),
    url(r'^cp/del/ad/(?P<pk>\d+)/$', DeleteAd.as_view(), name='AdDel'),
    url(r'^cp/del/cat/(?P<pk>\d+)/$', DeleteCategory.as_view(), name='CatDel'),
    url(r'^cp/login$', LoginBackend.as_view(), name='LoginBackend'),
    url(r'^cp/logout$', LogoutBackend.as_view(), name='LogoutBackend'),
    url(r'^cp/get_prices/$', GetRelatedPrices.as_view()),
    url(r'^cp/add_feature/$', FeatureAdd.as_view(), name='FeatureAdd'),
    url(r'^cp/list_feature/$', FeatureList.as_view(), name='FeatureList'),
    url(
        r'^cp/edit_feature/(?P<pk>\d+)/$',
        FeatureEdit.as_view(),
        name='FeatureEdit'
    ),
    url(
        r'^cp/del/feature/(?P<pk>\d+)/$',
        DeleteFeature.as_view(),
        name='FeatureDel'
    ),
    url(r'^cp/add_amenity/$', AmenityAdd.as_view(), name='AmenityAdd'),
    url(r'^cp/list_amenity/$', AmenityList.as_view(), name='AmenityList'),
    url(
        r'^cp/edit_amenity/(?P<pk>\d+)/$',
        AmenityEdit.as_view(),
        name='AmenityEdit'
    ),
    url(
        r'^cp/del/amenity/(?P<pk>\d+)/$',
        DeleteAmenity.as_view(),
        name='AmenityDel'
    ),

    url(r'^cp/list_place/$', PlaceList.as_view(), name='PlaceList'),
    url(r'^cp/add_place/$', PlaceAdd.as_view(), name='PlaceAdd'),
    url(
        r'^cp/edit_place/(?P<pk>\d+)/$',
        PlaceEdit.as_view(),
        name='PlaceEdit'
    ),
    url(
        r'^cp/del/place/(?P<pk>\d+)/$',
        DeletePlace.as_view(),
        name='PlaceDel'
    ),
)

django_project/core/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',

    # Enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Examples:
    # url(r'^brb/', include('brb.foo.urls')),

    url(r'', include('backend.urls')),
    url(r'', include('frontend.urls')),
    # required by django-select2
    url(r'^select2/', include('django_select2.urls')),
    url(r'^files-widget/', include('topnotchdev.files_widget.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT})
    )

django_project/backend/models.py
import logging
logger = logging.getLogger(__name__)
import datetime
from collections import namedtuple
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.gis.db import models

from topnotchdev import files_widget


class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Keywords(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class POI(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200, null=True, blank=True)
    largeBox = models.BooleanField(default=False)
    location = models.PointField(srid=4326)
    areaOfInterest = models.PolygonField(srid=4326)
    categories = models.ManyToManyField('Categories')
    keywords = models.ManyToManyField('Keywords')
    images = files_widget.ImagesField(null=True, blank=True)
    amenities = models.ManyToManyField('Amenity')

    objects = models.GeoManager()

    def __unicode__(self):
        return self.name

    def imagesThumbs(self):
        images = [[img.url, img.thumbnail('400x400').url] for img in (
            self.images.all())]
        return images

    def similarPois(self):
        """
        This function returns 4 POIs similar to referent POI.
        1) Find POIs that share at least one category with referent POI.
        2) Count how many keywords each similar POI shares with referent POI.
           extendedSimilarPoi named tuples are created on the way
           (with poi and countSharedKeywords data).
        3) Sort similar POIs by countSharedKeywords, limit to 4 POIs and
           extract poi from extendedSimilarPoi named tuples.
        """
        # Find POIs that share at least one category with referent POI.
        similarByCategory = POI.objects.filter(
            categories__id__in=self.categories.values_list('id')
        ).distinct().exclude(pk=self.pk)

        # For each POI similar by category count how many keywords
        # it shares with referent POI.
        referentPoiKeywords = self.keywords.values_list('id')
        extendedSimilarPoisList = []
        extendedSimilarPoi = namedtuple(
            'extendedSimilarPoi',
            'poi countSharedKeywords'
        )
        for poi in similarByCategory:
            countSharedKeywords = 0
            for keyword in poi.keywords.values_list('id'):
                if keyword in referentPoiKeywords:
                    countSharedKeywords += 1

            # Append similar POI (with matches info) to extendedSimilarPoisList
            extendedSimilarPoisList.append(
                extendedSimilarPoi(poi, countSharedKeywords)
            )

        return [sorted_poi.poi for sorted_poi in sorted(
            extendedSimilarPoisList,
            key=lambda similarPoi: similarPoi.countSharedKeywords,
            reverse=True)[:4]
        ]

    def openUntil(self):
        now = datetime.datetime.now()
        try:
            wt = Worktime.objects.get(
                poiid=self.pk,
                dow=now.weekday(),
                startTime__lte=now.time(),
                endTime__gte=now.time()
            )
            return 'open until {}'.format(wt.endTime.strftime('%I:%M%p'))
        except ObjectDoesNotExist:
            return 'Closed'

    def formatedHours(self):
        DAYS = (
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday',
            'Sunday'
        )
        hours = Worktime.objects.filter(poiid=self.pk).order_by('dow')
        fhours = []
        start_day = -1
        end_day = -1
        start_hour = -1
        end_hour = -1
        for hour in hours:
            text = {}
            if (hour.startTime != start_hour or hour.endTime != end_hour):
                if (start_day != -1):
                    if (start_day != end_day):
                        text['days'] = '{} - {}'.format(
                            DAYS[start_day][:3],
                            DAYS[end_day][:3]
                        )
                        if (start_hour != end_hour):
                            text['hours'] = '{} - {}'.format(
                                start_hour.strftime('%I:%M%p'),
                                end_hour.strftime('%I:%M%p')
                            )
                        else:
                            text['hours'] = 'Closed'
                    else:
                        text['days'] = '{}'.format(
                            DAYS[start_day],
                        )
                        if (start_hour != end_hour):
                            text['hours'] = '{} - {}'.format(
                                start_hour.strftime('%I:%M%p'),
                                end_hour.strftime('%I:%M%p')
                            )
                        else:
                            text['hours'] = 'Closed'
                    fhours.append(text)
                start_day = hour.dow
                end_day = hour.dow
                start_hour = hour.startTime
                end_hour = hour.endTime
            else:
                end_day = hour.dow
        text = {}
        if (start_day != end_day):
            text['days'] = '{} - {}'.format(
                DAYS[start_day][:3],
                DAYS[end_day][:3]
            )
            if (start_hour != end_hour):
                text['hours'] = '{} - {}'.format(
                    start_hour.strftime('%I:%M%p'),
                    end_hour.strftime('%I:%M%p')
                )
            else:
                text['hours'] = 'Closed'
        else:
            text['days'] = '{}'.format(
                DAYS[start_day],
            )
            if (start_hour != end_hour):
                text['hours'] = '{} - {}'.format(
                    start_hour.strftime('%I:%M%p'),
                    end_hour.strftime('%I:%M%p')
                )
            else:
                text['hours'] = 'Closed'
        fhours.append(text)
        return fhours


class Ad(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField(
        max_length=500,
        null=True,
        blank=True
    )
    location = models.PointField(srid=4326)
    areaOfInterest = models.PolygonField(srid=4326)
    categories = models.ManyToManyField('Categories')
    keywords = models.ManyToManyField('Keywords')
    images = files_widget.ImageField(null=True, blank=True)

    objects = models.GeoManager()

    def __unicode__(self):
        return self.name


class Worktime(models.Model):
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6

    DAYS = (
        (MONDAY, 'Monday'),
        (TUESDAY, 'Tuesday'),
        (WEDNESDAY, 'Wednesday'),
        (THURSDAY, 'Thursday'),
        (FRIDAY, 'Friday'),
        (SATURDAY, 'Saturday'),
        (SUNDAY, 'Sunday')
    )

    poiid = models.ForeignKey('POI')
    dow = models.SmallIntegerField(choices=DAYS, default=MONDAY)
    startTime = models.TimeField()
    endTime = models.TimeField()


class Price(models.Model):
    toddler = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    children = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    adults = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    students = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    seniors = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    poi = models.ForeignKey('POI')

    def formatedToddler(self):
        if (self.toddler == 0):
            return 'FREE'
        else:
            return '${}'.format(self.toddler)

    def formatedChildren(self):
        if (self.children == 0):
            return 'FREE'
        else:
            return '${}'.format(self.children)

    def formatedAdults(self):
        if (self.adults == 0):
            return 'FREE'
        else:
            return '${}'.format(self.adults)

    def formatedStudents(self):
        if (self.students == 0):
            return 'FREE'
        else:
            return '${}'.format(self.students)

    def formatedSeniors(self):
        if (self.seniors == 0):
            return 'FREE'
        else:
            return '${}'.format(self.seniors)


class FeaturePanel(models.Model):
    name = models.CharField(max_length=200)
    html = models.TextField()
    order = models.SmallIntegerField(default=0)

    def __unicode__(self):
        return self.name


class Amenity(models.Model):
    name = models.CharField(max_length=200)
    icon = files_widget.ImageField()
    order = models.SmallIntegerField(default=0)

    def __unicode__(self):
        return self.name


class Place(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    location = models.PointField(srid=4326)

    objects = models.GeoManager()

    def __unicode__(self):
        return self.name

django_project/backend/templates/OL-widget.html
<style type="text/css">{% block map_css %}
    #{{ id }}_map { width: {{ map_width }}px; height: {{ map_height }}px; }
    #{{ id }}_map .aligned label { float: inherit; }
    #{{ id }}_div_map { position: relative; vertical-align: top; float: {{ LANGUAGE_BIDI|yesno:"right,left" }}; }
    {% if not display_raw %}#{{ id }} { display: none; }{% endif %}
    .olControlEditingToolbar .olControlModifyFeatureItemActive {
        background-image: url("{{ STATIC_URL }}admin/img/gis/move_vertex_on.png");
        background-repeat: no-repeat;
    }
    .olControlEditingToolbar .olControlModifyFeatureItemInactive {
        background-image: url("{{ STATIC_URL }}admin/img/gis/move_vertex_off.png");
        background-repeat: no-repeat;
    }{% endblock %}
</style>

<div id="{{ id }}_div_map">
    <div id="{{ id }}_map"></div>
    <span class="clear_features"><a href="javascript:{{ module }}.clearFeatures()">Delete all Features</a></span>
    {% if display_raw %}<p>Debugging window (serialized value):</p>{% endif %}
    <textarea id="{{ id }}" class="vSerializedField required" cols="150" rows="10" name="{{ name }}">{{ serialized }}</textarea>
    <script type="text/javascript">
        {% block map_options %}var map_options = {};{% endblock %}
        {% block options %}var options = {
            geom_name: '{{ geom_type }}',
            id: '{{ id }}',
            map_id: '{{ id }}_map',
            map_options: map_options,
            map_srid: {{ map_srid }},
            name: '{{ name }}',
            base_layer: new OpenLayers.Layer.OSM()
        };
        {% endblock %}
        var {{ module }} = new MapWidget(options);
    </script>
</div>

django_project/backend/templates/backend-adlist.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
    <div class="col-md-12">
        <a class="btn btn-success" href="{% url 'AdAdd' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new Ad</a>
    </div>
</div>
<div class="row backend-space">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
            {% for ad in ads.all %}
                <tr>
                    <td><a href="{% url 'AdEdit' ad.id %}" >{{ ad.name }}</a></td>
                    <td><a class="btn btn-warning" href="{% url 'AdDel' ad.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-ad').addClass('active');
    });
</script>
{% endblock extra_js %}

django_project/backend/templates/backend-amenity-delete.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
<div class="col-md-4 col-md-offset-4">
        <form action="" method="post" role="form">
        {% csrf_token %}
            <p><h4>Are you sure you want to delete "{{ object.name }}"?</h4></p>
            <input type="submit" class="btn btn-danger btn-block" value="Yes" />
            <a href="{% url 'AmenityList' %}" class="btn btn-primary btn-block">No</a>
        </form>
    </div>
</div>
{% endblock %}

django_project/backend/templates/backend-amenitylist.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
    <div class="col-md-12">
        <a class="btn btn-success" href="{% url 'AmenityAdd' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new amenity</a>
    </div>
</div>
<div class="row backend-space">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
            {% for amenity in amenities.all %}
                <tr>
                    <td><a href="{% url 'AmenityEdit' amenity.id %}" >{{ amenity.name }}</a></td>
                    <td><a class="btn btn-warning" href="{% url 'AmenityDel' amenity.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-amenity').addClass('active');
    });
</script>
{% endblock extra_js %}

django_project/backend/templates/backend-base.html
{% load compressed %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title%} Big Red Bell  - administration{% endblock title%}</title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% compressed_css 'backend' %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}files_widget/css/widgets.css">
    <style type="text/css">
        body {
            padding-top: 50px;
        }
    </style>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Big Red Bell</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li id="menu-poi"><a href="{% url 'PoiList' %}">POIs</a></li>
        <li id="menu-ad"><a href="{% url 'AdList' %}">Ads</a></li>
        <li id="menu-cat"><a href="{% url 'CategoriesList' %}">Categories</a></li>
        <li id="menu-feature"><a href="{% url 'FeatureList' %}">Features</a></li>
        <li id="menu-amenity"><a href="{% url 'AmenityList' %}">Amenities</a></li>
        <li id="menu-place"><a href="{% url 'PlaceList' %}">Places</a></li>
      </ul>
      {% if user.is_authenticated %}
      <form class="navbar-form navbar-right" action="{% url 'LogoutBackend' %}" method="post">
      {% csrf_token %}
        <span id="hello-user">Hello, {{ user.username }}</span>
        <button type="submit" class="btn btn-primary">Logout</button>
      </form>
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="container">
{% compressed_js 'backend' %}
{% block content %}

{% endblock content %}
{% block extra_js %}
{% endblock extra_js %}
</div>

</body>
</html>

django_project/backend/templates/backend-categories_form.html
{% extends "backend-base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="backend-space">
        {% crispy form %}
    </div>
{% endblock content %}

{% block extra_js %}
    <script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-cat').addClass('active');
    });
    </script>
{% endblock extra_js %}

django_project/backend/templates/backend-categories_list.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
    <div class="col-md-12">
        <a class="btn btn-success" href="{% url 'CategoriesAdd' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new Category</a>
    </div>
</div>
<div class="row backend-space">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
            {% for category in categories.all %}
                <tr>
                    <td><a href="{% url 'CategoriesEdit' category.id %}" >{{ category.name }}</a></td>
                    <td><a class="btn btn-warning" href="{% url 'CatDel' category.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-cat').addClass('active');
    });
</script>
{% endblock extra_js %}

django_project/backend/templates/backend-feature-delete.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
<div class="col-md-4 col-md-offset-4">
        <form action="" method="post" role="form">
        {% csrf_token %}
            <p><h4>Are you sure you want to delete "{{ object.name }}"?</h4></p>
            <input type="submit" class="btn btn-danger btn-block" value="Yes" />
            <a href="{% url 'FeatureList' %}" class="btn btn-primary btn-block">No</a>
        </form>
    </div>
</div>
{% endblock %}

django_project/backend/templates/backend-featureform.html
{% extends "backend-base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="backend-space">
        {% crispy form %}
    </div>
{% endblock content %}

{% block extra_js %}
    <script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-feature').addClass('active');
    });
    </script>
{% endblock extra_js %}

django_project/backend/templates/backend-login.html
{% extends "backend-base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="backend-space">
	<div class="container">
		<div class="col-md-offset-4">
			{% crispy form %}
		</div>
	</div>
</div>
{% endblock content %}

django_project/backend/templates/backend-place-delete.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
<div class="col-md-4 col-md-offset-4">
		<form action="" method="post" role="form">
		{% csrf_token %}
			<p><h4>Are you sure you want to delete "{{ object.name }}"?</h4></p>
			<input type="submit" class="btn btn-danger btn-block" value="Yes" />
			<a href="{% url 'PlaceList' %}" class="btn btn-primary btn-block">No</a>
		</form>
	</div>
</div>
{% endblock %}

django_project/backend/templates/backend-placeform.html
{% extends "backend-base.html" %}
{% load compressed %}
{% load crispy_forms_tags %}
{% block content %}
{% compressed_js 'backend_form' %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/OpenLayers_2.13.1.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/OLMapWidget_custom.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}files_widget/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}files_widget/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}files_widget/js/widgets.js"></script>
    <div class="backend-space">
        {% crispy form %}
    </div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-place').addClass('active');
        // style buttons for image widget
        $('.fake-files-input').addClass('btn btn-success');
        $('.add-by-url-button').addClass('btn btn-info');
        // set map center if there is no POI location set
        if ( $('#id_location').val() == '') {
            geodjango_location.map.setCenter(new OpenLayers.LonLat('-13617943.738191467','6041590.467647917'), 11);
        }
    });
</script>
{% endblock extra_js %}

django_project/backend/templates/backend-placeslist.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
    <div class="col-md-12">
        <a class="btn btn-success" href="{% url 'PlaceAdd' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new Place</a>
    </div>
</div>
<div class="row backend-space">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
            {% for place in places.all %}
                <tr>
                    <td><a href="{% url 'PlaceEdit' place.id %}" >{{ place.name }}</a></td>
                    <td><a class="btn btn-warning" href="{% url 'PlaceDel' place.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-place').addClass('active');
    });
</script>
{% endblock extra_js %}

django_project/backend/templates/backend-poilist.html
{% extends "backend-base.html" %}

{% block content %}
<div class="row backend-space">
    <div class="col-md-12">
        <a class="btn btn-success" href="{% url 'PoiAdd' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add new POI</a>
    </div>
</div>
<div class="row backend-space">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                  <th>Name</th>
                  <th>Address</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
            {% for poi in pois.all %}
                <tr>
                    <td><a href="{% url 'PoiEdit' poi.id %}" >{{ poi.name }}</a></td>
                    <td>{{ poi.address }}</td>
                    <td><a class="btn btn-warning" href="{% url 'PoiDel' poi.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        // set menu item active
        $('#menu-poi').addClass('active');
    });
</script>
{% endblock extra_js %}